const blueprint = {
  name: "Trade-In Log",
  slug: "tradeinlog",
  fields: [
    { key: "Dealer", label: "Dealer", type: "string" },
    { key: "Inventory Type", label: "Inventory Type", type: "string" },
    { key: "Year", label: "Year", type: "string" },  // Represented as string for simplicity
    { key: "Make", label: "Make", type: "string" },
    { key: "Model", label: "Model", type: "string" },
    { key: "Sold Date", label: "Sold Date", type: "string" },
    { key: "Stock Number", label: "Stock Number", type: "string" },
    { key: "VIN", label: "VIN", type: "string" },
    { key: "First Name", label: "First Name", type: "string" },
    { key: "Middle Name", label: "Middle Name", type: "string" },
    { key: "Last Name", label: "Last Name", type: "string" },
    { key: "Daytime Phone", label: "Daytime Phone", type: "string" },
    { key: "Evening Phone", label: "Evening Phone", type: "string" },
    { key: "Cell Phone", label: "Cell Phone", type: "string" },
    { key: "Email", label: "Email", type: "string" },
    { key: "Alt Email", label: "Alt Email", type: "string" },
    { key: "City", label: "City", type: "string" },
    { key: "State", label: "State", type: "string" },
    { key: "Postal Code", label: "Postal Code", type: "string" },
    { key: "Total Gross", label: "Total Gross", type: "string" },
    { key: "Buyer Birth Date", label: "Buyer Birth Date", type: "string" },
    { key: "Gender", label: "Gender", type: "string" },
    { key: "Trade1 VIN", label: "Trade1 VIN", type: "string" },
    { key: "Trade1 Year", label: "Trade1 Year", type: "string" },
    { key: "Trade1 Make", label: "Trade1 Make", type: "string" },
    { key: "Trade1 Model", label: "Trade1 Model", type: "string" },
    { key: "Year_1", label: "Year_1", type: "string" },
    { key: "Make_1", label: "Make_1", type: "string" },
    { key: "Model_1", label: "Model_1", type: "string" },
    { key: "VIN_1", label: "VIN_1", type: "string" },
    { key: "ACV", label: "ACV", type: "string" },
    { key: "Trade Value", label: "Trade Value", type: "string" },
    { key: "Contract Date", label: "Contract Date", type: "string" }
  ]
}
